[features]
seeds = false
skip-lint = false
[programs.localnet]
blueshift_anchor_vault = "BBMxQgxz9ohpVJVUBksK6wgyfSLVfTdpWa6bUqAkrksR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/chris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
